### ISSUE TITLE
ci-info update

### ISSUE THREAD

**Issue by aslafy-z** [nuxt-contrib/std-env#4]
After digging a bit, I found out that the plugin you use to detect CI, does not support GitHub action with the pinned version. There was no release (https://github.com/watson/ci-info/issues/48) since support was implemented (https://github.com/watson/ci-info/pull/42). Consider pinning a commit, or forking the project.

**Comment by pi0** [comment]
Since ci-info is widely used, it is more preferred waiting for update instead of forking. Seems @sibiraj-s started working ~4 days ago ❤️  so giving more time for release

**Comment by Atinux** [comment]
Side note, it seems that GitHub actions now set `CI=true` since April 2020: https://github.blog/changelog/2020-04-15-github-actions-sets-the-ci-environment-variable-to-true/

**Comment by sibiraj-s** [comment]
Hi, I am a maintainer of the project but do not have publish permissions. I have raised a dispute to npm, the issue should be resolved shortly.

That said.

Detecting CI on Github Actions should work without latest version as it sets `CI=true` as mentioned by @Atinux . In case  if other changes in master is required, temporarily you can pin it to the latest commit for now.

**Comment by sibiraj-s** [comment]
Published a new version v3.0.0 just now.

**Comment by pi0** [comment]
Thanks! Landed by 2.3.0
